FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY app/model ./model
COPY data ./data

# Environment variables for local Docker detection
ENV DOCKER=1
ENV BACKEND_URL=http://backend:8000

CMD streamlit run app/frontend.py --server.address 0.0.0.0 --server.port ${PORT:-8501}




